### ISSUE TITLE
Labels

### ISSUE THREAD

**Issue by jbjz1** [daxAKAhackerman/n64-label-templates#37]
New to Github looks like this was the only way to message you, First off thanks these labels are amazing  thank you for your work. Second wondering if you had, or had any interested in making these same labels for super famicom and famicom I am collecting full sets for both and would be happy to help in anyway if you had any interest thanks again Joe.

**Comment by jbjz1** [comment]
My email is nbajams23@aol.com

**Comment by daxAKAhackerman** [comment]
Hello there 👋 Unfortunately, I only did N64 since it is the only console I collect for. I do not plan on collecting for another for the moment, so no other labels are planned.

**Comment by jbjz1** [comment]
Thanks for the response any way I can either bribe you  with some games for those systems , or pay your to make labels for it?

**Comment by daxAKAhackerman** [comment]
Thanks for the offer 😄 However, the sheer number of games for those systems would make creating custom labels for each a massive undertaking. The Nintendo 64 has a special place in my heart and that is why I didn't mind putting those tens of hours on creating the labels 😁 That being said, you are more than welcome to use the PSD format labels on my website to get you started in creating your own labels for the consoles you collect!

**Comment by jbjz1** [comment]
I  suck at picture editing/ formatting  unless you had like a YouTube for dummies on how to make one.  :( lol  but much appreciated .
